export const SET_INITIAL_STOCKS = 'SET_INITIAL_STOCKS';
export const UPDATE_STOCK_PRICES = 'UPDATE_STOCK_PRICES';
export const GENERATE_FAKE_TRADES = 'GENERATE_FAKE_TRADES';
export const ADD_TRADE = 'ADD_TRADE';
